# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:washer:0000A01F:viomi-v33:1

from enum import Enum


# class Device_Information(tuple, Enum):
#     Device_Manufacturer = (1, 1)
#     Device_Model = (1, 2)
#     Device_Serial_Number = (1, 3)
#     Current_Firmware_Version = (1, 4)


class Washer(tuple, Enum):
    Switch_Status = (2, 1)  # bool  # rwn
    Status = (2, 2)  # uint8  # rn
    Mode = (2, 3)  # uint8  # rwn
    Device_Fault = (2, 4)  # uint8  # rn
    Left_Time = (2, 5)  # uint16  # rn
    Target_Temperature = (2, 6)  # uint8  # rwn
    Spin_Speed = (2, 7)  # uint16  # rwn
    Drying_Time = (2, 8)  # uint8  # rwn
    Rinsh_Times = (2, 9)  # uint8  # rwn
    Door_State = (2, 11)  # uint8  # rn

    _Start_Wash = (2, 1)
    _Pause = (2, 2)


class Physical_Control_Locked(tuple, Enum):
    Physical_Control_Locked = (3, 1)  # bool  # rwn


class Custom(tuple, Enum):
    # 洗涤剂是否投放 = (4, 1)  # bool  # rnw
    # 洗涤剂投放量 = (4, 2)  # -dosage  # uint8  # rnw
    # 柔顺剂是否投放  = (4, 4)  # bool  # rnw
    # 柔顺剂投放量 = (4, 5)  # -dosage  # uint8  # rnw
    Appoint_Time = (4, 10)  # -time  # uint16  # rnw
    # 洗涤剂将耗尽  = (4, 15)  # -gone  # bool  # rn
    # 柔顺剂将耗尽  = (4, 16)  # -gone  # bool  # rn


class Washer_Status(int, Enum):
    docked = 0
    待机 = 1
    状态2 = 2
    状态3 = 3
    延迟 = 4
    状态5 = 5
    状态6 = 6
    洗涤运行 = 7
    状态8 = 8
    漂洗运行 = 9
    状态10 = 10
    脱水运行 = 11
    状态12 = 12
    状态13 = 13
    状态14 = 14
    繁忙 = 15
    状态16 = 16
    洗衣完成 = 17
    状态18 = 18
    状态19 = 19
    状态20 = 20
    状态21 = 21
    状态22 = 22
    状态23 = 23
    状态24 = 24
    状态25 = 25
    暂停 = 26
    错误 = 27


class Washer_Mode(int, Enum):
    黄金洗 = 0
    黄金烘 = 1
    洗加烘 = 2
    超快洗 = 3
    单脱水 = 4
    空气洗 = 5
    棉织物 = 9
    衬衣 = 11
    牛仔 = 12
    羊毛 = 14
    羽绒服 = 15
    除菌洗 = 16
    户外 = 19
    漂加脱 = 22
    桶清洁 = 23
    大物件 = 25
    丝绸 = 26
    护色 = 27


# class Washer_Device_Fault(int, Enum):
#     _0 = 0
#     _1 = 1
#     _2 = 2
#     _3 = 3
#     _4 = 4
#     _5 = 5
#     _6 = 6
#     _7 = 7
#     _8 = 8
#     _9 = 9
#     _10 = 10
#     _11 = 11
#     _12 = 12
#     _13 = 13
#     _14 = 14
#     _15 = 15
#     _16 = 16
#     _17 = 17
#     _18 = 18
#     _19 = 19
#     _20 = 20
#     _21 = 21
#     _22 = 22
#     _23 = 23
#     _24 = 24
#     _25 = 25
#     _26 = 26
#     _27 = 27
#     _28 = 28
#     _29 = 29
#     _30 = 30
#     _31 = 31
#     _32 = 32
#     _33 = 33
#     _34 = 34


# class Washer_Left_Time(int, Enum):
#     MIN = 0
#     MAX = 65535


# class Washer_Target_Temperature(int, Enum):
#     _0 = 0
#     _30 = 30
#     _40 = 40
#     _60 = 60
#     _80 = 80
#     _95 = 95


# class Washer_Spin_Speed(int, Enum):
#     _0 = 0
#     _500 = 500
#     _700 = 700
#     _900 = 900
#     _1200 = 1200
#     _1400 = 1400


class Washer_Drying_Time(int, Enum):
    不烘干 = 0
    智能烘干 = 1
    三十分钟 = 30
    一小时烘干 = 60
    一个半小时烘干 = 90
    两小时烘干 = 120


# class Washer_Rinsh_Times(int, Enum):
#     _0 = 0
#     _1 = 1
#     _2 = 2
#     _3 = 3
#     _4 = 4
#     _5 = 5
#     _6 = 6


# class Washer_Door_State(int, Enum):
#     Open = 1
#     Closed = 0


# class 自定义属性_detergent(int, Enum):
#     AFew = 0
#     Standard = 1
#     Quantity = 2


# class 自定义属性_softener(int, Enum):
#     AFew = 0
#     Standard = 1
#     Quantity = 2


# class 自定义属性_prepare(int, Enum):
#     MIN = 0
#     MAX = 24


ALL_SVCS = (Washer, Physical_Control_Locked, Custom)

