# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-m1:1

from enum import Enum


class Device_Information(tuple, Enum):
    Device_Manufacturer = (1, 1)
    Device_Model = (1, 2)
    Device_Serial_Number = (1, 3)
    Device_Name = (1, 4)
    Current_Firmware_Version = (1, 5)


class Air_Purifier(tuple, Enum):
    Switch_Status = (2, 1)  # bool  # rwn
    Mode = (2, 2)  # uint8  # rwn


class Environment(tuple, Enum):
    humidity = (3, 1)  # uint8  # rn
    aqi = (3, 2)  # float  # rn
    temperature = (3, 3)  # float  # rn


class Filter(tuple, Enum):
    Filter_Life_Level = (4, 1)  # uint8  # rn
    Filter_Used_Time = (4, 2)  # uint16  # rn


class Indicator_Light(tuple, Enum):
    Switch_Status = (5, 1)  # bool  # rwn
    Brightness = (5, 2)  # uint8  # rwn


class Alarm(tuple, Enum):
    Alarm = (6, 1)  # bool  # rwn


class Physical_Control_Locked(tuple, Enum):
    Physical_Control_Locked = (7, 1)  # bool  # rwn


class Air_Purifier_Favorite(tuple, Enum):
    Favorite_Fan_Level = (8, 1)  # uint8  # rwn


class Air_Purifier_Mode(int, Enum):
    Auto = 0
    Sleep = 1
    Favorite = 2


class Environment_Humidity(int, Enum):
    MIN = 0
    MAX = 100


class Environment_PM25(int, Enum):
    MIN = 0
    MAX = 600


class Environment_Temperature(int, Enum):
    MIN = -40
    MAX = 125
    STEP = 0.1


class Filter_Filter_Life_Level(int, Enum):
    MIN = 0
    MAX = 100


class Filter_Filter_Used_Time(int, Enum):
    MIN = 0
    MAX = 10000


class Indicator_Light_Brightness(int, Enum):
    brightest = 0
    glimmer = 1
    led_closed = 2


class Air_Purifier_Favorite_Favorite_Fan_Level(int, Enum):
    MIN = 0
    MAX = 10


ALL_SVCS = (Air_Purifier, Environment, Filter, Indicator_Light, Alarm, Physical_Control_Locked, Air_Purifier_Favorite)

