# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-v3:1

from enum import Enum


class Device_Information(tuple, Enum):
    Device_Manufacturer = (1, 1)
    Device_Model = (1, 2)
    Device_Serial_Number = (1, 3)
    Current_Firmware_Version = (1, 4)


class Fan(tuple, Enum):
    Switch_Status = (2, 1)  # bool  # rwn
    Fan_Level = (2, 2)  # uint8  # rwn
    Horizontal_Swing = (2, 3)  # bool  # rwn
    Horizontal_Angle = (2, 4)  # uint16  # rw
    Mode = (2, 5)  # uint8  # rw

    _Toggle = (2, 1)


class Physical_Control_Locked(tuple, Enum):
    Physical_Control_Locked = (3, 1)  # bool  # rwn


class Battery(tuple, Enum):
    Battery_Level = (4, 1)  # uint8  # rn
    Charging_State = (4, 2)  # uint8  # rn


class Fan_Fan_Level(int, Enum):
    MIN = 1
    MAX = 4


class Fan_Horizontal_Angle(int, Enum):
    MIN = 30
    MAX = 120


class Fan_Mode(int, Enum):
    Straight_Wind = 0
    Natural_Wind = 1


class Battery_Battery_Level(int, Enum):
    MIN = 0
    MAX = 100


class Battery_Charging_State(int, Enum):
    Charging = 1
    Charge_Complete = 2


ALL_SVCS = (Device_Information, Fan, Physical_Control_Locked, Battery)

