# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-fa1:3

from enum import Enum


class Device_Information(tuple, Enum):
    #Device_Manufacturer = (1, 1)
    Device_Model = (1, 2)
    Device_Serial_Number = (1, 3)
    Current_Firmware_Version = (1, 4)


class Fan(tuple, Enum):
    Switch_Status = (2, 1)  # bool  # rwn
    Level = (2, 2)  # uint8  # rwn
    Horizontal_Swing = (2, 3)  # bool  # rwn
    Vertical_Swing = (2, 4)  # bool  # rwn
    Horizontal_Angle = (2, 5)  # uint16  # rwn
    Vertical_Angle = (2, 6)  # uint8  # rwn
    Mode = (2, 7)  # uint8  # rwn
    Status = (2, 8)  # uint8  # rn
    Device_Fault = (2, 9)  # uint8  # rn
    Brightness = (2, 10)  # uint8  # rwn
    Alarm = (2, 11)  # bool  # rwn


class Physical_Control_Locked(tuple, Enum):
    Physical_Control_Locked = (6, 1)  # bool  # rwn
    Current_Physical_Control_Lock = (6, 2)  # bool  # rn


class Other(tuple, Enum):
    定时 = (5, 2)  # uint32  # rnw
    左右回正开关 = (5, 4)  # bool  # rwn
    上下回正开关 = (5, 5)  # bool  # rnw
    _设定风扇左右转动7_5度 = (5, 6)  # w
    _设定风扇水平转动7_5度 = (5, 7)  # w
    _one = (5, 8)  # -key-cycle  # bool  # w
    _one2 = (5, 9)  # -key-back  # bool  # w
    stepless = (5, 10)  # -fan-level  # uint8  # rnw


class Custom(tuple, Enum):
    _toggle = (7, 1)  # bool  # w

    _toggle1 = (7, 1)  # -switch  # in=[1]
    _toggle2 = (7, 2)  # -mode  # in=[1]
    _toggle3 = (7, 3)  # -level  # in=[1]


class Fan_Level(int, Enum):
    MIN = 1
    MAX = 5


class Fan_Horizontal_Angle(int, Enum):
    MIN = 0
    MAX = 120


class Fan_Vertical_Angle(int, Enum):
    MIN = 0
    MAX = 90


class Fan_Mode(int, Enum):
    Natural_Wind = 0
    Straight_Wind = 1


class Fan_Status(int, Enum):
    Idle = 1
    Busy = 2


class Fan_Device_Fault(int, Enum):
    Nofaults = 0
    Stuck = 1
    _2 = 2


class Fan_Brightness(int, Enum):
    MIN = 0
    MAX = 1


class _定时(int, Enum):
    MIN = 0
    MAX = 8


class _stepless(int, Enum):
    MIN = 1
    MAX = 100


ALL_SVCS = (Device_Information, Fan, Physical_Control_Locked, Other, Custom)

