# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-za3:1

from enum import Enum


class Device_Information(tuple, Enum):
    #Device_Manufacturer = (1, 1)
    Device_Model = (1, 2)
    Device_Serial_Number = (1, 3)
    Current_Firmware_Version = (1, 4)


class Fan(tuple, Enum):
    Switch_Status = (2, 1)  # bool  # rwn
    Level = (2, 2)  # uint8  # rwn
    Horizontal_Swing = (2, 3)  # bool  # rwn
    Horizontal_Angle = (2, 4)  # uint16  # rwn
    Mode = (2, 5)  # uint8  # rw


class Physical_Control_Locked(tuple, Enum):
    Physical_Control_Locked = (3, 1)  # bool  # rw


class Alarm(tuple, Enum):
    Alarm = (4, 1)  # bool  # rwn


class Indicator_Light(tuple, Enum):
    Switch_Status = (5, 1)  # bool  # rwn


class Fan_Level(int, Enum):
    MIN = 1
    MAX = 4


class Fan_Horizontal_Angle(int, Enum):
    MIN = 0
    MAX = 120


class Fan_Mode(int, Enum):
    Straight_Wind = 0
    Natural_Wind = 1


ALL_SVCS = (Device_Information, Fan, Physical_Control_Locked, Alarm, Indicator_Light)

