# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:washer:0000A01F:viomi-v13:2

from enum import IntEnum

SRV_Device_Information = 1
PROP_Device_Manufacturer = 1
PROP_Device_Model = 2
PROP_Device_Serial_Number = 3
PROP_Current_Firmware_Version = 4

SRV_Washer = 2
PROP_Switch_Status = 1 #bool #rwn
PROP_Status = 2 #uint8 #rn
class VALUE_Status(IntEnum):
    关机 = 0
    待机 = 1
    状态2 = 2
    状态3 = 3
    延迟 = 4
    状态5 = 5
    状态6 = 6
    洗涤运行 = 7
    状态8 = 8
    漂洗运行 = 9
    状态10 = 10
    脱水运行 = 11
    状态12 = 12
    状态13 = 13
    状态14 = 14
    状态15 = 15
    状态16 = 16
    洗衣完成 = 17
    状态18 = 18
    状态19 = 19
    状态20 = 20
    状态21 = 21
    状态22 = 22
    状态23 = 23
    状态24 = 24
    繁忙 = 25
    暂停 = 26
    错误 = 27
PROP_Mode = 3 #uint8 #rwn
class VALUE_Mode(IntEnum):
    黄金洗 = 0
    黄金烘 = 1
    洗加烘 = 2
    超快洗 = 3
    单脱水 = 4
    空气洗 = 5
    低温烘 = 6
    暖烘 = 7
    快速洗烘 = 8
    棉织物 = 9
    快洗 = 10
    衬衣 = 11
    牛仔 = 12
    内衣 = 13
    羊毛 = 14
    羽绒服 = 15
    除菌洗 = 16
    童衣洗 = 17
    精细织物 = 18
    运动服 = 19
    雪纺 = 20
    棉节能 = 21
    漂加脱 = 22
    桶清洁 = 23
PROP_Device_Fault = 4 #uint8 #rn
class VALUE_Device_Fault(IntEnum):
    Fault0 = 0
    Fault1 = 1
    Fault2 = 2
    Fault3 = 3
    Fault4 = 4
    Fault5 = 5
    Fault6 = 6
    Fault7 = 7
    Fault8 = 8
    Fault9 = 9
    Fault10 = 10
    Fault11 = 11
    Fault12 = 12
    Fault13 = 13
    Fault14 = 14
    Fault15 = 15
    Fault16 = 16
    Fault17 = 17
    Fault18 = 18
    Fault19 = 19
    Fault20 = 20
    Fault21 = 21
    Fault22 = 22
    Fault23 = 23
    Fault24 = 24
    Fault25 = 25
    Fault26 = 26
    Fault27 = 27
    Fault28 = 28
PROP_Left_Time = 5 #uint16 #rn
class VALUE_Left_Time(IntEnum):
    MIN = 0
    MAX = 1440
PROP_Target_Temperature = 6 #uint8 #rwn
class VALUE_Target_Temperature(IntEnum):
    Tempe0 = 0
    Tempe30 = 30
    Tempe40 = 40
    Tempe60 = 60
    Tempe90 = 90
PROP_Spin_Speed = 7 #uint16 #rwn
class VALUE_Spin_Speed(IntEnum):
    Speed0 = 0
    Speed400 = 400
    Speed600 = 600
    Speed800 = 800
    Speed1000 = 1000
    Speed1200 = 1200
    Speed1400 = 1400
PROP_Drying_Time = 8 #uint8 #rwn
class VALUE_Drying_Time(IntEnum):
    不烘干 = 0
    智能烘干 = 1
    三十分钟 = 30
    一小时烘干 = 60
    一个半小时烘干 = 90
    两小时烘干 = 120
    三小时烘干 = 180
    四小时烘干 = 240
PROP_Rinsh_Times = 9 #uint8 #rwn
class VALUE_Rinsh_Times(IntEnum):
    Times0 = 0
    Times1 = 1
    Times2 = 2
    Times3 = 3
    Times4 = 4
    Times5 = 5
    Times6 = 6
    Times7 = 7
PROP_Speed_Level = 10 #uint8 #rwn
class VALUE_Speed_Level(IntEnum):
    Level1 = 1
    Level2 = 2
    Level3 = 3
    Level4 = 4
    Level5 = 5
PROP_Door_State = 11 #uint8 #rn
class VALUE_Door_State(IntEnum):
    Open = 1
    Closed = 2
PROP_Power_Consumption = 12 #uint16 #rn
class VALUE_Power_Consumption(IntEnum):
    MIN = 0
    MAX = 20000
PROP_Water_Consumption = 13 #uint16 #rn
class VALUE_Water_Consumption(IntEnum):
    MIN = 0
    MAX = 1000
PROP_Working_Time = 14 #uint16 #rn
class VALUE_Working_Time(IntEnum):
    MIN = 0
    MAX = 1440
ACTION_Start_Wash = 1 #in=[3] #out=[3]
ACTION_Pause = 2 #in=[3] #out=[3]

SRV_Physical_Control_Locked = 3
PROP_Physical_Control_Locked = 1 #bool #rwn

SRV_自定义属性 = 4
PROP_洗涤剂是否投放 = 1 #bool #rnw
PROP_洗涤剂投放量 = 2 #uint8 #rnw
class VALUE_洗涤剂投放量(IntEnum):
    Value = 2
PROP_洗涤剂消耗量= 3 #uint8 #rn
class VALUE_洗涤剂消耗量(IntEnum):
    MIN = 0
    MAX = 200
PROP_柔顺剂是否投放 = 4 #bool #rnw
PROP_柔顺剂投放量 = 5 #uint8 #rnw
class VALUE_柔顺剂投放量(IntEnum):
    少量 = 0
    标准 = 1
    多量 = 2
PROP_柔顺剂消耗量 = 6 #uint8 #rn
class VALUE_柔顺剂消耗量(IntEnum):
    MIN = 0
    MAX = 200
PROP_disinfectant = 7 #bool #rnw
PROP_消毒剂投放量 = 8 #uint8 #rnw
class VALUE_消毒剂投放量(IntEnum):
    少量 = 0
    标准 = 1
    多量 = 2
PROP_消毒剂消耗量 = 9 #uint8 #rn
class VALUE_消毒剂消耗量(IntEnum):
    MIN = 0
    MAX = 200
PROP_预约完成时间 = 10 #uint32 #rnw
class VALUE_预约完成时间戳(IntEnum):
    MIN = 0
    MAX = 4294836225
PROP_模式 = 11 #uint8 #
class VALUE_模式(IntEnum):
    MIN = 0
    MAX = 100
PROP_耗电量 = 12 #uint16 #
class VALUE_耗电量(IntEnum):
    MIN = 0
    MAX = 65535
PROP_耗水量 = 13 #uint8 #
class VALUE_耗水量(IntEnum):
    MIN = 0
    MAX = 255
PROP_工作时长 = 14 #uint16 #
class VALUE_工作时长(IntEnum):
    MIN = 0
    MAX = 65535
PROP_洗涤剂将耗尽 = 15 #bool #rn
PROP_柔顺剂将耗尽 = 16 #bool #rn
PROP_消毒剂将耗尽 = 17 #bool #rn

SRV_用户按键上报 = 5
PROP_按键属性 = 1 #rn
PROP_按键值 = 2 #uint8 #rn
class VALUE_按键值(IntEnum):
    MIN = 0
    MAX = 255
PROP_按键时长 = 3 #uint16 #rn
class VALUE_按键时长(IntEnum):
    MIN = 0
    MAX = 65535

#ALL_PROPS = {2: {1: 'Switch_Status', 2: 'Status', 3: 'Mode', 4: 'Device_Fault', 5: 'Left_Time', 6: 'Target_Temperature', 7: 'Spin_Speed', 8: 'Drying_Time', 9: 'Rinsh_Times', 10: 'Speed_Level', 11: 'Door_State', 12: 'Power_Consumption', 13: 'Water_Consumption', 14: 'Working_Time'}, 3: {1: 'Physical_Control_Locked'}, 4: {1: '洗涤剂是否投放', 2: '洗涤剂投放量', 3: '洗涤剂消耗量（ml）', 4: '柔顺剂是否投放【暂无】', 5: '柔顺剂投放量【暂无】', 6: '柔顺剂消耗量（ml）【暂无】', 7: 'disinfectant', 8: '消毒剂投放量【暂无】', 9: '消毒剂消耗量（ml）【暂无】', 10: '预约完成时间戳__1._下行非0表示开始预约；2._下行0表示取消预约', 15: '洗涤剂将耗尽', 16: '柔顺剂将耗尽【暂无】', 17: '消毒剂将耗尽【暂无】'}, 5: {1: '按键属性', 2: '按键值', 3: '按键时长(毫秒)'}}
ALL_PROPS = {2: {2: '工作状态', 3: '洗涤模式', 4: '设备错误', 5: '剩余时间', 6: '洗涤水温', 7: '脱水转速', 8: '烘干时间', 9: '漂净时间', 11: '开门状态', 12: '电量消耗', 13: '用水消耗', 14: '工作时间'}, 3: {1: '按键锁定'}, 4: {10: '预约完成时间戳'}}
